services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        container_name: elantiguo-backend
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - elantiguo
        depends_on:
            - mysql
        extra_hosts:
            - "host.docker.internal:host-gateway"  

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: mysql-elantiguo
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./docker/db:/var/lib/mysql
        networks:
            - elantiguo

networks:
    elantiguo:
        driver: bridge